/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed": "#d5e3fd",
        "on-surface-variant": "#45464d",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#0d1c2f",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fb",
        "primary-container": "#131b2e",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed-dim": "#ffb690",
        "on-secondary": "#ffffff",
        "tertiary-container": "#0d1c2f",
        "outline-variant": "#c6c6cd",
        "on-secondary-container": "#5c2400",
        "surface-container-highest": "#e0e3e5",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#783200",
        "outline": "#76777d",
        "primary": "#000000",
        "secondary": "#9d4300",
        "on-secondary-fixed": "#341100",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#76859b",
        "surface-tint": "#565e74",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#7c839b",
        "secondary-fixed": "#ffdbca",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-container": "#fd761a",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed-dim": "#b9c7e0"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "stack-sm": "4px",
        "base": "8px",
        "stack-lg": "24px",
        "stack-md": "12px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "40px"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg": ["Poppins"],
        "headline-md": ["Poppins"],
        "headline-lg": ["Poppins"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Poppins"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
